services:
  thermal-printer-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aco-thermal-printer-service
    ports:
      - "3003:3000"
    environment:
      PORT: "3000"
      API_ACCESS_TOKEN: "test-token-1234"
    volumes:
      - backend-storage:/app/storage
    restart: unless-stopped

volumes:
  backend-storage:
