import type {
  PrinterAdapter,
  PrinterAdapterResult,
  ReconnectSchedule,
} from "./printer.adapter";
import type {
  ConnectionInfo,
  ConnectionMode,
  PrinterCommandPayload,
  PrinterError,
  PrinterErrorCode,
  PrinterHealth,
} from "../types/printer.types";

export abstract class MockPrinterAdapter implements PrinterAdapter {
  private connection: ConnectionInfo = {
    mode: null,
    state: "disconnected",
    reconnectAttempts: 0,
    nextReconnectAt: null,
    lastConnectedAt: null,
  };

  private health: PrinterHealth = {
    paper: "ok",
    cover: "closed",
    temperature: "normal",
  };

  protected constructor(public readonly mode: ConnectionMode) {}

  async connect(): Promise<ConnectionInfo> {
    this.connection = {
      mode: this.mode,
      state: "connected",
      reconnectAttempts: 0,
      nextReconnectAt: null,
      lastConnectedAt: new Date().toISOString(),
    };

    return this.connection;
  }

  async send(command: PrinterCommandPayload): Promise<PrinterAdapterResult> {
    if (this.connection.state !== "connected" || !this.connection.mode) {
      return {
        success: false,
        error: this.createError("COMM_ERROR"),
        command,
      };
    }

    return {
      success: true,
      message: `Command payload generated by ${this.mode.toUpperCase()} mock adapter`,
      command,
    };
  }

  getHealth(): PrinterHealth {
    return this.health;
  }

  getConnection(): ConnectionInfo {
    return this.connection;
  }

  setHealth(health: Partial<PrinterHealth>): PrinterHealth {
    this.health = {
      ...this.health,
      ...health,
    };

    return this.health;
  }

  scheduleReconnect(): ReconnectSchedule {
    const reconnectAttempts = this.connection.reconnectAttempts + 1;
    const delayMs = Math.min(30_000, 1000 * 2 ** (reconnectAttempts - 1));

    this.connection = {
      mode: this.connection.mode,
      state: "reconnecting",
      reconnectAttempts,
      nextReconnectAt: new Date(Date.now() + delayMs).toISOString(),
      lastConnectedAt: this.connection.lastConnectedAt,
    };

    return {
      connection: this.connection,
      delayMs,
    };
  }

  private createError(code: PrinterErrorCode): PrinterError {
    const messages: Record<PrinterErrorCode, PrinterError> = {
      PAPER_OUT: {
        code,
        detail: "No paper detected",
        userMessage: "Printer paper is out. Please insert a new roll.",
      },
      PAPER_JAM: {
        code,
        detail: "Paper path is blocked",
        userMessage: "Paper jam detected. Please clear the paper path.",
      },
      COVER_OPEN: {
        code,
        detail: "Printer cover is open",
        userMessage: "Printer cover is open. Please close it before printing.",
      },
      OVERHEAT: {
        code,
        detail: "Print head temperature is too high",
        userMessage: "Printer is overheated. Please wait before retrying.",
      },
      COMM_ERROR: {
        code,
        detail: "Printer communication failed",
        userMessage: "Printer connection failed. The service will retry automatically.",
      },
      UNKNOWN_COMMAND: {
        code,
        detail: "Unsupported printer command",
        userMessage: "The printer command is not supported.",
      },
    };

    return messages[code];
  }
}
